### ISSUE TITLE
Unable to compile with openssl 1.0.2g-1ubuntu4.9

### ISSUE THREAD

**Issue by kristen1980** [openresty/openresty#320]
I am using
` ./configure -j2 --with-pcre-jit --with-http_image_filter_module --add-dynamic-module=/home/kristen/openresty/nginx-hmac-secure-link`

on "make -j2" I get:

```
../encrypted-session-nginx-module-0.07/src/ngx_http_encrypted_session_cipher.c: In function ‘ngx_http_encrypted_session_aes_mac_encrypt’:
../encrypted-session-nginx-module-0.07/src/ngx_http_encrypted_session_cipher.c:29:30: error: storage size of ‘ctx’ isn’t known
     EVP_CIPHER_CTX           ctx;
                              ^
../encrypted-session-nginx-module-0.07/src/ngx_http_encrypted_session_cipher.c:29:30: warning: unused variable ‘ctx’ [-Wunused-variable]
../encrypted-session-nginx-module-0.07/src/ngx_http_encrypted_session_cipher.c: In function ‘ngx_http_encrypted_session_aes_mac_decrypt’:
../encrypted-session-nginx-module-0.07/src/ngx_http_encrypted_session_cipher.c:136:30: error: storage size of ‘ctx’ isn’t known
     EVP_CIPHER_CTX           ctx;
                              ^
../encrypted-session-nginx-module-0.07/src/ngx_http_encrypted_session_cipher.c:136:30: warning: unused variable ‘ctx’ [-Wunused-variable]
objs/Makefile:2020: recipe for target 'objs/addon/src/ngx_http_encrypted_session_cipher.o' failed
make[2]: *** [objs/addon/src/ngx_http_encrypted_session_cipher.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/home/kristen/openresty/openresty-1.13.6.1/build/nginx-1.13.6'
Makefile:8: recipe for target 'build' failed
make[1]: *** [build] Error 2
make[1]: Leaving directory '/home/kristen/openresty/openresty-1.13.6.1/build/nginx-1.13.6'
Makefile:4: recipe for target 'all' failed
make: *** [all] Error 2

```

Not sure where to go from here.

**Comment by spacewander** [comment]
@kristen1980 
The error message looks like that you are compiling with OpenSSL 1.1.0, but you report that you are using OpenSSL 1.0.2g...

Anyway, currently the only way to work around it is compiling with a lower OpenSSL version.

**Comment by kristen1980** [comment]
You're right. I now see the open issue. Works with lower OpenSSL version. Thanks for the quick reply!
