### ISSUE TITLE
Error in make because of openssl 1.1, what's the "solution"?

### ISSUE THREAD

**Issue by unisqu** [openresty/openresty#341]
Used to be able to make and compile easily but no idea why I'm using the latest version with Ubuntu 16.04 with errors below. Please help. What do I need to "apt-get install"? i've done apt-get install openssl libssl-dev already.
```

../encrypted-session-nginx-module-0.07/src/ngx_http_encrypted_session_cipher.c: In function 'ngx_http_encrypted_session_aes_mac_encrypt':
../encrypted-session-nginx-module-0.07/src/ngx_http_encrypted_session_cipher.c:29:30: error: storage size of 'ctx' isn't known
     EVP_CIPHER_CTX           ctx;
                              ^
../encrypted-session-nginx-module-0.07/src/ngx_http_encrypted_session_cipher.c:29:30: warning: unused variable 'ctx' [-Wunused-variable]
../encrypted-session-nginx-module-0.07/src/ngx_http_encrypted_session_cipher.c: In function 'ngx_http_encrypted_session_aes_mac_decrypt':
../encrypted-session-nginx-module-0.07/src/ngx_http_encrypted_session_cipher.c:136:30: error: storage size of 'ctx' isn't known
     EVP_CIPHER_CTX           ctx;
                              ^
../encrypted-session-nginx-module-0.07/src/ngx_http_encrypted_session_cipher.c:136:30: warning: unused variable 'ctx' [-Wunused-variable]

```

**Comment by unisqu** [comment]
ok i found out that i'm using openssl 1.1

what do you suggest I do with this? what's the alternative? downgrade to openssl 1.0? I would like it to work on ubuntu 16.04. what's the best way forward?

**Comment by unisqu** [comment]
will use
--with-openssl=

Thanks.
