### ISSUE TITLE
Openresty 1.25.3.2 build errors

### ISSUE THREAD

**Issue by p-thamke** [openresty/openresty#1090]
We are building kong 3.9.1 with openresty 1.25.3.2.
On hitting service api through kong 3.9.1, we got following run-time error in logs:
"2025/11/25 13:30:22 [error] 10601#0: 1289 failed to run balancer_by_lua: .../luarocks/share/lua/5.1/kong/init.lua:1432: attempt to call upvalue 'enable_keepalive' (a nil value)
stack traceback:
.../luarocks/share/lua/5.1/kong/init.lua:1432: in function 'balancer'
balancer_by_lua(nginx-kong.conf:72):2: in main chunk while connecting to upstream, client: 172.17.0.32, server: kong, request: "GET /v1/api HTTP/1.1", host: "url:port", request_id: ****************************** "

Based on analysis, we understood "enable_keepalive" is available as part of "lua-resty-core" in openresty. 
On integrating "lua-resty-core" to build with Openresty 1.25.3.2, it threw error saying "stream-lua-nginx-module is required" as seen below:

<img width="1878" height="131" alt="Image" src="https://github.com/user-attachments/assets/cf575b29-b9ec-43c5-bf0c-7ddd889ffa8e" />

We added "stream-lua-nginx-module" for openresty 1.25.3.2 with "--add-module" option. Now building this throws error as follows:
/tmp/nginx-stream-lua-module/src/ngx_stream_lua_proxy_ssl_verifyby.c: In function 'ngx_stream_lua_ffi_proxy_ssl_free_verify_cert':
/tmp/nginx-stream-lua-module/src/ngx_stream_lua_proxy_ssl_verifyby.c:894:47: error: parameter name omitted
ngx_stream_lua_ffi_proxy_ssl_free_verify_cert(void *)
^~~~~~
make[2]: *** [objs/Makefile:3697: objs/addon/src/ngx_stream_lua_proxy_ssl_verifyby.o] Error 1

We request to share any inputs to handle these errors for open source openresty code and build it successfully.

Thank you.

**Comment by p-thamke** [comment]
Hi @HanadaLee , Thank you for the response.
Can you please suggest which module supports enable_keepalive for openresty 1.25.3.2..
