### ISSUE TITLE
ngx_openresty-1.7.0.1 does not compile on Max OSX 10.9.2

### ISSUE THREAD

**Issue by kmarellapudi** [openresty/openresty#57]
Here is the error reported during the 'make' 

```
objs/ngx_modules.o \
-Wl,-rpath,/usr/local/openresty/luajit/lib -L/usr/local/pcre-8.33/lib -L/Users/kmarellapudi/LetsDoIt/ngx_openresty-1.7.0.1/build/luajit-root/usr/local/openresty/luajit/lib -lluajit-5.1 -lm -pagezero_size 10000 -image_base 100000000 -lpcre -lssl -lcrypto -lz
```

Undefined symbols for architecture x86_64:
  "_SSL_CTX_set_next_protos_advertised_cb", referenced from:
      _ngx_http_ssl_merge_srv_conf in ngx_http_ssl_module.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: **\* [objs/nginx] Error 1
make[1]: **\* [build] Error 2
make: **\* [all] Error 2

I did follow the special instruction for darwin users about installing pcre.

**Comment by imvvk** [comment]
HI,  I also can't  compile  when I use the ngx_openresty-1.7.0.2  in Mac 10.11.1 (El Caption) , the openssl is 1.0.2d , it throw " 
src/event/ngx_event_openssl.c error: too few arguments to function call
/usr/local/include/openssl/x509v3.h:741:1: note: 'X509_check_host' declared here
"
when I use the ngx_openresty-1.9.3.2  that is OK .

**Comment by agentzh** [comment]
@imvvk Glad the new OpenResty releases work for you.
