### ISSUE TITLE
undefined reference to `OpenSSL_add_all_digests'

### ISSUE THREAD

**Issue by iyyapa** [openresty/openresty#878]
Hi Folks,

I am working on the SHA512 password encryption feature implementation and did the code changes for SHA512 hashing. 
For compilation added the makefile dependencies and facing build errors. 
Where we are using LIBPAM0.76 and OpenSSL is 1.0.2h.  The changes are working fine in LIBPAM1.3 and tried to accommodate the changes in LIBPAM0.76 version seeing errors.

Can someone help us resolve the issue?

sha512.c: At top level:
sha512.c:365: warning: no previous prototype for 'sha512_crypt'
libmd5.so: undefined reference to `OpenSSL_add_all_digests'
libmd5.so: undefined reference to `EVP_MD_CTX_create'
libmd5.so: undefined reference to `EVP_MD_CTX_destroy'
libmd5.so: undefined reference to `EVP_get_digestbyname'
libmd5.so: undefined reference to `EVP_DigestInit_ex'
libmd5.so: undefined reference to `EVP_DigestFinal_ex'
libmd5.so: undefined reference to `EVP_DigestUpdate'
collect2: ld returned 1 exit status
make[12]: *** [unix_chkpwd] Error 1
make[11]: *** [all] Error 1

**Comment by zhuizhuhaomeng** [comment]
LIBPAM is not included by openresty.
I think you need to create an issue in the LIBPAM repo.
