### ISSUE TITLE
1.9.11rc0 compile error

### ISSUE THREAD

**Issue by webeau** [openresty/openresty#148]
I am trying to compile using my standard script and libressl-2.3.2.  This script has worked for all previous Openresty compiles but now I get the following error.  I am not trying to get lua to do anything with certs or ssl (as I have similar errors in my search for a solution).  This intended to be a stock Openresty install.

objs/ngx_modules.o \
-L/opt/src/ngx_openresty/openresty-1.9.11.1rc0/build/luajit-root/usr/local/openresty/luajit/lib -Wl,-rpath,/usr/local/openresty/luajit/lib -lrt -Wl,-E -ldl -lpthread -lcrypt -L/usr/local/lib -ldrizzle -L/opt/src/ngx_openresty/openresty-1.9.11.1rc0/build/luajit-root/usr/local/openresty/luajit/lib -lluajit-5.1 -lm -ldl -lbrotlienc -lstdc++ -L/usr/local/lib -lMagickWand-6.Q16 -lMagickCore-6.Q16 -L/usr/local/lib -lMagickWand-6.Q16 -lMagickCore-6.Q16 -lgd -lqrencode -luuid /opt/src/pcre-8.38/.libs/libpcre.a /opt/src/libressl-2.3.2/.openssl/lib/libssl.a /opt/src/libressl-2.3.2/.openssl/lib/libcrypto.a /opt/src/zlib/libz.a -lxml2 -lxslt -lexslt -lgd -lGeoIP -latomic_ops \
-Wl,-E -fstack-protector -L/usr/local/lib -L/usr/lib/x86_64-linux-gnu/perl/5.20/CORE -lperl -ldl -lm -lpthread -lc -lcrypt \
-Wl,-E
objs/addon/src/ngx_http_lua_module.o: In function `ngx_http_lua_merge_srv_conf':
/opt/src/ngx_openresty/openresty-1.9.11.1rc0/build/nginx-1.9.11/../ngx_lua-0.10.1rc0/src/ngx_http_lua_module.c:893: undefined reference to `SSL_CTX_set_cert_cb'
objs/addon/src/ngx_http_lua_ssl_certby.o: In function `ngx_http_lua_ffi_ssl_clear_certs':
/opt/src/ngx_openresty/openresty-1.9.11.1rc0/build/nginx-1.9.11/../ngx_lua-0.10.1rc0/src/ngx_http_lua_ssl_certby.c:553: undefined reference to `SSL_certs_clear'
objs/addon/src/ngx_http_lua_ssl_certby.o: In function `ngx_http_lua_ffi_ssl_set_der_certificate':
/opt/src/ngx_openresty/openresty-1.9.11.1rc0/build/nginx-1.9.11/../ngx_lua-0.10.1rc0/src/ngx_http_lua_ssl_certby.c:623: undefined reference to `SSL_add0_chain_cert'

**Comment by webeau** [comment]
To avoid any confusion that this may be LibreSSL related, I also tried the same using the stable release 2.2.6:

objs/ngx_modules.o \
-L/opt/src/ngx_openresty/openresty-1.9.11.1rc0/build/luajit-root/usr/local/openresty/luajit/lib -Wl,-rpath,/usr/local/openresty/luajit/lib -lrt -Wl,-E -ldl -lpthread -lcrypt -L/usr/local/lib -ldrizzle -L/opt/src/ngx_openresty/openresty-1.9.11.1rc0/build/luajit-root/usr/local/openresty/luajit/lib -lluajit-5.1 -lm -ldl -lbrotlienc -lstdc++ -L/usr/local/lib -lMagickWand-6.Q16 -lMagickCore-6.Q16 -L/usr/local/lib -lMagickWand-6.Q16 -lMagickCore-6.Q16 -lgd -lqrencode -luuid /opt/src/pcre-8.38/.libs/libpcre.a /opt/src/libressl-2.2.6/.openssl/lib/libssl.a /opt/src/libressl-2.2.6/.openssl/lib/libcrypto.a /opt/src/zlib/libz.a -lxml2 -lxslt -lexslt -lgd -lGeoIP -latomic_ops \
-Wl,-E -fstack-protector -L/usr/local/lib -L/usr/lib/x86_64-linux-gnu/perl/5.20/CORE -lperl -ldl -lm -lpthread -lc -lcrypt \
-Wl,-E
objs/addon/src/ngx_http_lua_module.o: In function `ngx_http_lua_merge_srv_conf':
/opt/src/ngx_openresty/openresty-1.9.11.1rc0/build/nginx-1.9.11/../ngx_lua-0.10.1rc0/src/ngx_http_lua_module.c:893: undefined reference to `SSL_CTX_set_cert_cb'
objs/addon/src/ngx_http_lua_ssl_certby.o: In function `ngx_http_lua_ffi_ssl_clear_certs':
/opt/src/ngx_openresty/openresty-1.9.11.1rc0/build/nginx-1.9.11/../ngx_lua-0.10.1rc0/src/ngx_http_lua_ssl_certby.c:553: undefined reference to `SSL_certs_clear'
objs/addon/src/ngx_http_lua_ssl_certby.o: In function `ngx_http_lua_ffi_ssl_set_der_certificate':
/opt/src/ngx_openresty/openresty-1.9.11.1rc0/build/nginx-1.9.11/../ngx_lua-0.10.1rc0/src/ngx_http_lua_ssl_certby.c:623: undefined reference to `SSL_add0_chain_cert'
collect2: error: ld returned 1 exit status

**Comment by webeau** [comment]
Sorry for multiple posts.  I hope to save you time.  I tried this exact same compile on 1.9.7.3 and get the same error.  1.9.7.1 compiles without error.  However, 1.9.7.2 does produce the same compile error.

Please let me know if there is any more information that may help run this error down.

**Comment by webeau** [comment]
Again, sorry, but this appears to be a known issue with Openresty and Libressl.  I am closing the issue.

**Comment by agentzh** [comment]
@webeau Fixed the compilation errors in git master of lua-nginx-module by disabling features unsupported by LibreSSL.
